### PR TITLE
Remove jQuery requirement.

### PR DESCRIPTION
**Pull request by rwjblue**

### CODE REVIEW

**Comment by rwjblue** [comment]
Simpler diff (this includes lots of whitespace changes) here: https://github.com/ember-cli/ember-cli-qunit/pull/136/files?w=1

**Comment by trentmwillis** [comment]
@rwjblue what about IE8 support as mentioned in #40?

**Comment by rwjblue** [comment]
@trentmwillis - I was under the impression we dropped IE8 support with ember-cli-qunit@2.0.0.

**Comment by rwjblue** [comment]
Ember itself dropped support sometime mid-last year (2015-06-15)

**Comment by trentmwillis** [comment]
I don't believe we did, I thought we were keeping it around for 1.13 apps. I'm fine with dropping, just want to make sure it was intentional.

**Comment by rwjblue** [comment]
It wasn't really, I just thought we had already dropped support. I can revert if folks have issue with it.  Gonna play wait and see I think for now...

**Comment by stefanpenner** [comment]
schweet!

**Pull request merged**
