### PR TITLE
Use ember install

### PR DESCRIPTION
**Pull request by martndemus**

### CODE REVIEW

**Comment by kellyselden** [comment]
Depending on support, you might want toake mention of `ember install:addon` for cli versions below 0.2.3.

**Comment by martndemus** [comment]
@kellyselden After submitting this PR I noticed there was also #64, that PR also addresses your issue.

**Comment by rwjblue** [comment]
Thank you!

**Comment by kellyselden** [comment]
@martndemus Good find. Thanks.

**Pull request merged**
