### PR TITLE
Move ember testing preview window to be under the running tests

### PR DESCRIPTION
**Pull request by TayHobbs**

### CODE REVIEW

**Comment by mattjmorrison** [comment]
:+1: This is awesome, I love it! Thanks @TayHobbs

**Comment by mattjmorrison** [comment]
Also, just for documentation - this addresses this issue https://github.com/ember-cli/ember-cli/pull/3014

**Comment by mattjmorrison** [comment]
@rwjblue @stefanpenner Sorry to bug you, have either of you guys had a chance to take a look at this to see if it is an acceptable solution?

**Comment by stefanpenner** [comment]
i would like this to be toggleable.

**Comment by TayHobbs** [comment]
@stefanpenner toggleable between these two views? 
screen shot 2015-03-24 at 10 03 25 am
screen shot 2015-03-24 at 10 05 17 am

Also, what would you name the toggle option?

**Comment by stefanpenner** [comment]
> @stefanpenner toggleable between these two views?

yes

> Also, what would you name the toggle option?
>  Merge pull request

I am not sure, naming is hard. Maybe something like "float test pane"?

**Comment by TayHobbs** [comment]
Closed because this was resolved in #53.

**Pull request closed without merging**
