### PR TITLE
Exclude the project name when requiring files

### PR DESCRIPTION
**Pull request by marcioj**
Applying the changes of ember-cli/ember-cli-test-loader#10 here

### CODE REVIEW

**Comment by rwjblue** [comment]
Thanks!

**Comment by stefanpenner** [comment]
@rwjblue i think we are good for a release, should I cut?

**Comment by rwjblue** [comment]
Working on it, trying to setup ember-cli-release to make this as simple as `ember release`...

**Comment by stefanpenner** [comment]
kk

**Pull request merged**
