### PR TITLE
Remove backwards compat shims.

### PR DESCRIPTION
**Pull request by rwjblue**
Preparing for for ember-cli-qunit@2.0.0.

### CODE REVIEW

**Comment by rwjblue** [comment]
@Turbo87 / @trentmwillis - r?

**Comment by Turbo87** [comment]
seems fine to me 👍

**Comment by trentmwillis** [comment]
:+1:, seems like maybe Travis has an old version of Ember-CLI cached?

**Comment by rwjblue** [comment]
Since 2.0.0 has been cut, I think this will have to hold for 3.0.0.

**Comment by trentmwillis** [comment]
@rwjblue any chance you could rebase this and get it green so that we can release with the QUnit 2.0 update (which will need to be a major version)?

**Pull request merged**
