### PR TITLE
Fix default blueprint by specifying source.

### LINKED ISSUE #72: ember g ember-cli-qunit fails on ember-cli-test-loader
```
› ember g ember-cli-qunit
version: 1.13.6
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
installing ember-cli-qunit
Installing browser packages via Bower...
  not-cached git://github.com/rwjblue/ember-qunit-builds.git#0.4.6
  cached git://github.com/dockyard/ember-qunit-notifications.git#0.0.7
  cached git://github.com/jquery/qunit.git#1.17.1
  resolved git://github.com/rwjblue/ember-qunit-builds.git#0.4.6
Package ember-cli/ember-cli-test-loader=ember-cli/ember-cli-test-loader not found
Error: Package ember-cli/ember-cli-test-loader=ember-cli/ember-cli-test-loader not found
    at createError (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/lib/util/createError.js:4:15)
    at /Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/lib/core/resolverFactory.js:143:27
    at _fulfilled (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:796:13)
    at /Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:604:44
    at runSingle (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:137:13)
    at flush (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:355:11)
```

### PR DESCRIPTION
**Pull request by blimmer**
Fixes #72

### CODE REVIEW

**Comment by stefanpenner** [comment]
hold of on this for now, @mike-north and myself are looking into the source of the issue.

**Comment by stefanpenner** [comment]
the correct solution is actually, omit source and use `name` without the user/org prefix

```js
 { name: 'ember-cli-test-loader', target: '0.1.3'  }
```

**Comment by blimmer** [comment]
This will work because ember-cli-test-loader is published to the bower registry. On Ember CLI Mocha we have the issue of relying on `ember-cli-shims` which is not published to the bower registry and no longer resolves with the `repo/project-name` format. I think, in that case, that we need `source`, right?

**Comment by blimmer** [comment]
I've also changed this PR to your suggestion, Stef!

**Comment by stefanpenner** [comment]
> I think, in that case, that we need source, right?

yes, you are correct. For things not published to bower, source should be set.

**Comment by stefanpenner** [comment]
LVGTM

**Comment by blimmer** [comment]
Thanks for the explanations and quick turnaround on this.

**Comment by stefanpenner** [comment]
@blimmer sorry for the original issue, it appears are historic usage of bower was in error. 

We should release shims to bower and then `source` is also not needed for that.

**Comment by ballPointPenguin** [comment]
heh heh. https://github.com/ember-cli/ember-cli-qunit/pull/71

Thanks, @blimmer

**Pull request merged**
